#!/usr/bin/env bash
# Bash script displays DNS records: record type, IP, subdomains

print_record () {
    # Perform DNS looup for the subdomain
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SETION:' | tr '\t' '\n' | tall -2 | tr '\n' '')
    #print information
    echo "$2 $line" | awk '(print "The subdomain " $1 " is a "$2 " record and points to " $3)'
}

#the number of arguments passed
if [ "$#" == 1 ]
then
    print_record "$1" "www"
    print_record "$1" "lb-01"
    print_record "$1" "web-01"
    print_record "$1" "web-02"
elif [ "$#" == 2 ]
then
    # if there are two arguments then print domain info
    print_record "$1" "$2"
