#!/usr/bin/env bash
# Transfer file from a client to server

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# variables
file_path=$1
ip_address=$2
username=$3
ssh_key_path=$4

# disable strict host key checking

scp -o "StricHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$ip_address:~/"

# check for success

if [ $? eq 0]
then
	echo "Successful"
else
	echo "Not Successful"
fi
