#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
