#!/usr/bin/env bash
# install nginx and  listening on port 80

sudo apt-get -y update && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
