#!/usr/bin/env bash
# Configures an nginx server so that /redirect_me redirects to a new page

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
line="\\\trewrite ^/redirect_me https://github.com/adiomi90 permanent;"
sudo sed -i "/listen 80 default_server;/a $line" /etc/nginx/sites-enabled/default

sudo service nginx restart
