#!/usr/bin/env bash
# Configures my nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/inde.html
replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/adiomi90 permanent;"

sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_replace="listen 80 default_server;\n\terror_page 404\/404.html;\n\tlocation = \/404.html; {\n\troot \/var/www/html; \n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
